ERR_INVALID_REQUEST = 1001
ERR_NOT_FOUND = 1002
ERR_ALREADY_EXISTS = 1003
ERR_AUTH = 2001
ERR_PERMISSION = 2002
ERR_INTERNAL = 5001

__all__ = [
    "ERR_ALREADY_EXISTS",
    "ERR_AUTH",
    "ERR_INTERNAL",
    "ERR_INVALID_REQUEST",
    "ERR_NOT_FOUND",
    "ERR_PERMISSION",
]
