DEFAULT_PERMISSION_CODES = [
    "user:list",
    "user:read",
    "user:create",
    "user:update",
    "user:delete",
    "user:assign_role",
    "role:list",
    "role:read",
    "role:create",
    "role:update",
    "role:delete",
    "role:assign_permission",
    "permission:list",
    "permission:read",
]